// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Node 24 hace type stripping nativo: no necesita tsx ni compilación.
    //
    // El --disable-warning silencia MODULE_TYPELESS_PACKAGE_JSON, que Node
    // emite al importar los .ts de lib/ porque el package.json no declara
    // "type". Son cinco líneas de ruido que enterraban los mensajes reales
    // del seed. Se desactiva solo ese aviso, no todos.
    seed: "node --disable-warning=MODULE_TYPELESS_PACKAGE_JSON prisma/seed.mts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
