// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Node 24 hace type stripping nativo: no necesita tsx ni compilación.
    seed: "node prisma/seed.mts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
